# Generated by Django 4.0.4 on 2022-04-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='مقدار عددی قیمت هر کالا')),
                ('unit', models.IntegerField(choices=[(0, 'Toman'), (1, 'Dollar'), (2, 'Uro')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('color', models.IntegerField(choices=[(0, 'Blue'), (1, 'Green'), (2, 'Gold')])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brnad_products', to='product.productbrnd')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='product.productcategory')),
                ('prices', models.ManyToManyField(blank=True, related_name='prices_products', to='product.productprice')),
            ],
        ),
    ]
